title: MYMI
author: Forestry.io
email: info@mymi.org.au
description: >-
MYMI (Monash Young MedTech Innovators) is an interdisciplinary community of undergraduates, postgraduates and early career researchers (ECRs) dedicated to achieving
positive impact through medical technology and biomedical innovation. Based at Monash University, founded in late 2018.
baseurl:  "" # the subpath of your site, e.g. /blog
url: "https://www.mymi.org.au/" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
